Chore: loosen security-check
allthings/node-sdk pull request #434
Opened 2021-07-15 18:55 UTC by DmitryMarkov

2021-07-15 19:19 UTC, DmitryMarkov commented
@svlapin nb: test degraded despite no code changes were made

2021-07-16 06:26 UTC, svlapin commented on test/docker-compose.yml
> +    image: allthings/rope:fix_issues2
Why using tagged `rope` image?

2021-07-16 07:31 UTC, DmitryMarkov commented on test/docker-compose.yml
> +    image: allthings/rope:fix_issues2
@svlapin The test was failing getting permissions, so I had guess it might be RoPe repository issue, I reverted back recent dependency updates, but it didn't help.

2021-07-22 12:03 UTC, DmitryMarkov commented
tests should be running again after https://allthings.atlassian.net/browse/APP-6882 is resolved

2021-07-23 11:05 UTC, adashst approved these changes
LGTM Thanks! 👍

2021-07-23 11:29 UTC, peinwag requested changes
thanks for the changes.

imho we should rather remove the lines from the tests completely

2021-07-23 11:29 UTC, peinwag commented on src/rest/methods/agent.test.ts
> +    expect(result.roles).toBeUndefined()
sorry to hijack this, but I'd rather remove this line completely since this property is no longer available in the response it's just confusing here.

2021-07-23 11:29 UTC, peinwag commented on src/rest/methods/agent.test.ts
> +    expect(result.roles).toBeUndefined()
same here

2021-07-23 11:54 UTC, peinwag approved these changes

2021-07-23 14:14 UTC, merged